project:
  type: book
  output-dir: docs

book:
  title: Quantiles, Networks, Time
  author: 
    - name: andrew p blake 
      email: andrewpeterblake@gmail.com
      affiliations:
        - name: ccbs
          address: bank of england
  date: "2024"
  status: "In Preparation"
  chapters:
    - index.qmd
    - intro.qmd
    - R2021.qmd
    - BVAR.qmd
    - QR.qmd
    - Stemp.qmd
    - Maps.qmd
    - summary.qmd
    - references.qmd

bibliography: CourseRefs.bib

format:
  html:
    theme: 
      light: sandstone
      dark: darkly
  pdf:
    documentclass: book

editor: visual

