project:
  type: book
  output-dir: docs

book:
  title: Quantiles, Networks, Time
  author: 
    - name: andrew p blake 
      email: andrewpeterblake@gmail.com
      affiliations:
        - name: ccbs
          address: bank of england
  date: "2024"
  status: "In Preparation"
  
  chapters:
    - index.qmd
    - part: "Methods matter"
      chapters:
        - intro.qmd
        - R2021.qmd
        - ssm.qmd
        - RegressionLemma.qmd
        - Kalman.qmd
    - part: "Quantiles"
      chapters:
        - QR.qmd
        - Gibbs.qmd
        - CK.qmd
        - SMH.qmd
    - part: "Networks"
      chapters: 
        - Stemp.qmd
        - Maps.qmd
    - part: "Time"
      chapters: 
      - BK.qmd
      - BVAR.qmd
      - Dynare.qmd
    - part: "End matter"
      chapters:
      - summary.qmd
      - references.qmd
  appendices:
    - Appendix1.qmd
    - LinAlg.qmd

bibliography: [CourseRefs.bib, BVAR.bib, Refs2.bib, refsBayes.bib]

format:
  html:
    theme: 
      light: sandstone
      dark: darkly
  pdf:
    documentclass: book
    toc: true
    lof: true
    lot: true
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
    
editor: visual

