project:
  type: book
  output-dir: docs

book:
  title: "Quantiles, Networks, Time"
  author: "andrew p blake"
  date: "2024"
  status: "In Preparation"
  cover-image: Specs.GIF
  chapters:
    - index.qmd
    - intro.qmd
    - R2021.qmd
    - QR.qmd
    - Stemp.qmd
    - summary.qmd
    - references.qmd

bibliography: CourseRefs.bib

format:
  html:
    theme: 
      light: sandstone
      dark: darkly
  pdf:
    documentclass: book

editor: visual

