project:
  type: book
  output-dir: docs

book:
  title: "Quantiles"
  author: "andrew p. blake"
  date: "18/05/2023"
  cover-image: Specs.GIF
  chapters:
    - index.qmd
    - intro.qmd
    - R2021.qmd
    - QR.qmd
    - Stemp.qmd
    - summary.qmd
    - references.qmd

bibliography: CourseRefs.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book

editor: visual

