# Causal Inference in Statistics: Pearl, Glymour, Jewell

Outline how to solve the @Primer exercises in R.

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE)
```

## Study question 1.3.2

Data:
```{r cars, echo = TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
ed <- tibble(Gender = c("M","M","M","M","F","F","F","F"),
             eLevel = c("U","H","C","G","U","H","C","G"),
             num    = c(112,231,595,242,136,189,763,172)) %>%
  mutate(total = sum(num))
```
which we tabulate as
```{r}
ed %>%
  kable()
```

## Exercises and answers

### Find $P(eLevel = H)$

```{r kableA}
ed %>%
  filter(eLevel == "H") %>%
  mutate(p_H = n()/total) %>%
  kable()
```

### Find $P(eLevel = H\ \vee \ Gender = F)$

```{r kableB}
ed %>%
  filter(Gender == "F" | eLevel == "H") %>%
  mutate(p_HorF = sum(num)/total) %>%
  kable()
```

### Find $P(eLevel = H\ |\ Gender = F)$

```{r kableC}
ed %>%
  filter(Gender == "F") %>%
  mutate(tcond = sum(num)) %>% 
  filter(eLevel == "H") %>%
  mutate(p_HgivenF = sum(num)/tcond) %>%
  kable()
```

### Find $P(Gender = F\ | \ eLevel = H)$

```{r kableD, fig.align='center'}
ed %>%
  filter(eLevel == "H") %>%
  mutate(tcond = sum(num)) %>% 
  filter(Gender == "F") %>%
  mutate(p_FgivenH = sum(num)/tcond) %>%
  kable()
```
